# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-02 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myppp', '0002_auto_20150809_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paonter', models.CharField(blank=True, default=b'', max_length=25, null=True, verbose_name='Painter')),
            ],
            options={
                'verbose_name': 'Painter',
                'verbose_name_plural': 'Painters',
            },
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'ordering': ['color'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='my_ppp',
            options={'ordering': ['name'], 'verbose_name': 'My PPP', 'verbose_name_plural': 'My PPP'},
        ),
        migrations.AddField(
            model_name='my_ppp',
            name='painter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myppp.Painters'),
        ),
    ]
