# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-02 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myppp', '0003_auto_20160102_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painters',
            old_name='paonter',
            new_name='painter',
        ),
    ]
